# baseURL = "https://sunvdong.github.io/"
baseURL = "https://www.vdong.xyz/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 是否使用 emoji 代码
enableEmoji = true
enableRobotsTXT = true # 允许爬虫抓取到搜索引擎，建议 true
enableGitInfo = true # 获取每个文件的git修改信息
# 网站标题
title = "我的灵感记录"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[params]
  # DoIt 主题版本
  version = "0.4.X"
  enablePWA = false
    # 主页配置
  [params.home]
    # DoIt 新增 | 0.2.0 RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # 主页显示头像的 URL
      # 将你的头像文件放置于 static 或者 assets 目录下
      # 文件路径是相对于 static 或者 assets 目录的
      avatarURL = "/imgs/avatar.webp"
      # DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题
      subtitle = "这是我的个人网站"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
      disclaimer = ""

  [params.page]
    # 评论系统设置
    [params.page.comment]
      enable = true
      # Waline 评论系统设置 (https://waline.js.org)
      [params.page.comment.waline]
        enable = true
        serverURL = "https://comment.vdong.xyz/"
        pageview = true
        comment = true
        emoji = ['https://i.whaoot.com/emojis/qq/']
        # emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
        # meta = ['nick', 'mail', 'link']
        # requiredMeta = []
        # login = 'enable'
        # wordLimit = 0
        # pageSize = 10
        # imageUploader = false
        # highlighter = false
        # texRenderer = false

  # DoIt 新增 | 0.2.0 List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  [params.search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia", "fuse")
    type = "fuse"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = "搜索文章标题或内容..."
    # DoIt 新增 | 0.2.1 最大结果数目
    maxResultLength = 10
    # DoIt 新增 | 0.2.3 结果内容片段长度
    snippetLength = 50
    # DoIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # DoIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.fuse]
      # DoIt 新增 | 0.2.12 https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false

  # 作者的社交信息设置
  [params.social]
    GitHub = "SunVdong"
    # Bilibili = "285732103"
    Email = "sunvdong@qq.com"
    RSS = true

  [params.page.toc]
    # 是否使用目录
    enable = true
    # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true
  
  [params.footer]
    enable = true
    hugo = true
    hostedOn = '<a title="Github Pages" href="https://github.com/SunVdong/sunvdong.github.io" target="_blank" rel="noopener noreferrer">GitHub Pages</a>'
    copyright = true
    icp = '<a href="https://beian.miit.gov.cn/" target="_blank">豫ICP备18016268号-2</a>'
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-PSTPB5Y974"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "links"
    pre = ""
    post = ""
    name = "友链"
    url = "/links"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "mm"
    pre = ""
    post = ""
    name = "树洞"
    url = "https://mm.vdong.xyz/"
    title = ""
    weight = 5
  [[menu.main]]
    identifier = "pad"
    pre = ""
    post = ""
    name = "pad"
    url = "https://pad.vdong.xyz/"
    title = ""
    weight = 6

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[frontmatter]
  lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[taxonomies]
  tag = "tags"
  category = "categories"
